<?php
/**
 * ContractTest.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DPAE.
 *
 * Connection of Troops & DPAE
 *
 * OpenAPI spec version: 1.0.0-oas3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DPAE;

/**
 * ContractTest Class Doc Comment.
 *
 * @category    Class
 * @description Contract
 *
 * @author      Swagger Codegen team
 *
 * @see        https://github.com/swagger-api/swagger-codegen
 */
class ContractTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Contract".
     */
    public function testContract()
    {
    }

    /**
     * Test attribute "startDate".
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "startTime".
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "endDate".
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "code".
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "healthService".
     */
    public function testPropertyHealthService()
    {
    }
}
