<?php
/**
 * UploadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DPAE
 *
 * Connection of Troops & DPAE
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UploadTest Class Doc Comment
 *
 * @category    Class
 * @description Upload
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UploadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Upload"
     */
    public function testUpload()
    {
    }

    /**
     * Test attribute "xmlnscct"
     */
    public function testPropertyXmlnscct()
    {
    }

    /**
     * Test attribute "xmlnsrxdt"
     */
    public function testPropertyXmlnsrxdt()
    {
    }

    /**
     * Test attribute "xmlnsrxorg"
     */
    public function testPropertyXmlnsrxorg()
    {
    }

    /**
     * Test attribute "xmlnsrxpadr"
     */
    public function testPropertyXmlnsrxpadr()
    {
    }

    /**
     * Test attribute "xmlnsrxpers"
     */
    public function testPropertyXmlnsrxpers()
    {
    }

    /**
     * Test attribute "xmlnsrxphadr"
     */
    public function testPropertyXmlnsrxphadr()
    {
    }

    /**
     * Test attribute "xmlnsxsi"
     */
    public function testPropertyXmlnsxsi()
    {
    }

    /**
     * Test attribute "indicator"
     */
    public function testPropertyIndicator()
    {
    }

    /**
     * Test attribute "dues_group"
     */
    public function testPropertyDuesGroup()
    {
    }
}
